# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
RUN npm ci --omit=dev
COPY . .
RUN npm run build && \
    rm -rf node_modules

# Stage 2: Production
FROM nginx:alpine

# Копируем статику
COPY --from=builder /app/out /usr/share/nginx/html
COPY docker/nginx/nginx-spa.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]