import { TFilterOptions } from './types';

/**
 * Дефолтный объект с которым работает компонент фильтров.
 * Компонент отдает объект в таком виде, если какое-то поле не определено(пользователь не выбрал фильтр), то значение свойства будет null
 */
export const initialFilterOptions: TFilterOptions = {
    name: null,
    max_price: null,
    min_price: null,
    flag: null,
    type: null,
    exploitation_type: null,
    class_formula: null,
    ice_power: null,
    purpose: null,
    was_registered: null,
    register_valid_until: null,
    vessel_status: null,
    project_number: null,
    building_number: null,
    max_building_year: null,
    min_building_year: null,
    building_place: null,
    port_adress_country: null,
    port_adress_city: null,
    vessel_location_country: null,
    vessel_location_city: null,
    imo_number: null,
    min_overall_length: null,
    max_overall_length: null,
    min_overall_width: null,
    max_overall_width: null,
    min_board_height: null,
    max_board_height: null,
    material: null,
    min_deadweight: null,
    max_deadweight: null,
    min_dock_weight: null,
    max_dock_weight: null,
    min_full_displacement: null,
    max_full_displacement: null,
    min_gross_tonnage: null,
    max_gross_tonnage: null,
    min_num_additional_engines: null,
    max_num_additional_engines: null,
    min_num_engines: null,
    max_num_engines: null,
    min_power: null,
    max_power: null,
    min_maximum_speed: null,
    max_maximum_speed: null,
    cargo_tanks: null,
    min_total_capacity_cargo_tanks: null,
    max_total_capacity_cargo_tanks: null,
    second_bottom: null,
    second_sides: null,
    min_carrying: null,
    max_carrying: null,
    superstructures: null,
    min_passangers_avialable: null,
    max_passangers_avialable: null,
    technical_documentation: null
};
